@startuml pert5
:start;
:pilihan menu;

    if (pilih makanan) then
        :makanan;
        :soto ayam;
        :nasi goreng;
    else if (pilih minuman) then
        :minuman;
        :es jeruk;
        :teh manis;
    else if (exit) then
        :exit;
    else
        :Display "Pilihan Salah!";
    endif;

@enduml